src/main/java/no/nav/fo/veilarbaktivitet/service/AktivitetAppService.java, src/main/java/no/nav/fo/veilarbaktivitet/service/AktivitetService.java, src/test/java/no/nav/fo/veilarbaktivitet/service/AktivitetAppServiceTest.java, src/test/java/no/nav/fo/veilarbaktivitet/service/AktivitetServiceTest.java
Veileder kan nå oppdatere Kanal på avtalte møter
=> KAIZEN-0: Veileder oppdatere mer på avtale møter

src/main/java/no/nav/veilarbaktivitet/db/dao/MoteSmsDAO.java, src/main/java/no/nav/veilarbaktivitet/domain/SmsAktivitetData.java, src/main/java/no/nav/veilarbaktivitet/service/CroneService.java, src/main/java/no/nav/veilarbaktivitet/service/MoteSMSService.java, src/main/java/no/nav/veilarbaktivitet/service/VarselQueService.java, src/test/java/no/nav/veilarbaktivitet/db/dao/MoteSMSDAOTest.java, src/test/java/no/nav/veilarbaktivitet/service/MoteSMSServiceTest.java
=> [FO-2505] mote sms bugfiks

src/main/java/no/nav/veilarbaktivitet/db/dao/MoteSmsDAO.java, src/main/java/no/nav/veilarbaktivitet/domain/KanalDTO.java, src/main/java/no/nav/veilarbaktivitet/domain/SmsAktivitetData.java, src/main/java/no/nav/veilarbaktivitet/service/MoteSMSService.java, src/main/java/no/nav/veilarbaktivitet/service/VarselQueService.java, src/main/resources/db/migration/V1_31__mote_pamidelse_form.sql, src/test/java/no/nav/veilarbaktivitet/service/MoteSMSServiceTest.java
Skal sende og lagre møtetype for servicemelding.
Skal oppdateres til og sende på nytt etter vi har får oppdatert varsel
=> [FO-3009] sender og lagrer motetype for servicemelding del 1

src/main/java/no/nav/veilarbaktivitet/config/FilterConfig.java
Gjorde også om rekkefølge på filtere slik at vi logger 401 kall
=> Legg til srvveilarboppfolging som godkjent systembruker

pom.xml
Endringer foreslått av dependabot pluss la til properties for [junit|quartz].version.
=> Minor version bumps on JUnit and Quartz.

src/main/java/no/nav/veilarbaktivitet/avtaltMedNav/AvtaltMedNavController.java, src/main/java/no/nav/veilarbaktivitet/avtaltMedNav/AvtaltMedNavService.java, src/main/java/no/nav/veilarbaktivitet/domain/AktivitetData.java, src/main/java/no/nav/veilarbaktivitet/domain/Person.java, src/main/java/no/nav/veilarbaktivitet/mappers/AktivitetDTOMapper.java, src/main/java/no/nav/veilarbaktivitet/service/AktivitetService.java, src/main/java/no/nav/veilarbaktivitet/service/AuthService.java, src/test/java/no/nav/veilarbaktivitet/avtaltMedNav/AvtaltMedNavServiceTest.java, src/test/java/no/nav/veilarbaktivitet/avtaltMedNav/ForhaandsorienteringDTOControllerTest.java, src/test/java/no/nav/veilarbaktivitet/controller/AktivitetsplanRSTest.java, src/test/java/no/nav/veilarbaktivitet/domain/PersonTest.java, src/test/java/no/nav/veilarbaktivitet/service/AktivitetServiceTest.java, src/test/java/no/nav/veilarbaktivitet/service/AuthServiceTest.java
Kaster den gamle PR-en. Denne er basert på en rebase av mine endringer på seneste dev. Tilhører https://trello.com/c/LizBkoBd
=> lagtInnAv endretAv fix 

src/main/java/no/nav/veilarbaktivitet/db/Database.java, src/test/java/no/nav/veilarbaktivitet/avtaltMedNav/AvtaltMedNavServiceTest.java, src/test/java/no/nav/veilarbaktivitet/avtaltMedNav/ForhaandsorienteringDTOControllerTest.java
Legger tilbake gammel test og sletter ubrukt kode for å øke testdekning, pga sonarcloud bygg som feiler
=> Øke testdekning for å rette sonarcloud feil

src/main/java/no/nav/veilarbaktivitet/avtaltMedNav/ForhaandsorienteringDAO.java, src/test/java/no/nav/veilarbaktivitet/avtaltMedNav/ForhaandsorienteringDAOTest.java, src/test/java/no/nav/veilarbaktivitet/controller/AktivitetsplanRSTest.java, src/test/java/no/nav/veilarbaktivitet/service/AktivitetAppServiceTest.java
=> Sonar feil fiks

src/main/java/no/nav/veilarbaktivitet/avtaltMedNav/ForhaandsorienteringDAO.java, src/test/java/no/nav/veilarbaktivitet/avtaltMedNav/ForhaandsorienteringDAOTest.java
=> Håndtere mer enn 1000 forhåndsorienteringer

src/main/java/no/nav/veilarbaktivitet/config/MessageQueueConfig.java
https://trello.com/c/GzeGticf/296-bytte-mq-servicebruker-p%C3%A5-veilarbaktivitet-og-veilarbdialog
Må bestille bruker i basta før denne kan merges. Ordner det på mandag før vi merger denne.
=> fikse mq bruker

src/main/java/no/nav/veilarbaktivitet/avtaltMedNav/AvtaltMedNavService.java
https://trello.com/c/kE8MMJOX/322-fikse-metrikker-som-ikke-funker
=> Fikser feil i metrikk

nais-q.yaml, nais.yaml
This reverts commit 220eda4f7ae479ef6d0ce8d12cdae76eabf9d7f6.
Reverter fordi vi må også endre channel navn i mq for at dette skal fungere, da er det bedre å vente
=> Revert "bytter til team namespace (#189)"

patcher/FAGSYSTEM-170502.sql
Denne patchen setter nyeste av de duplikate aktivitetene til gjeldende.
https://trello.com/c/V5NmBGxj
=> DB patch for å fikse duplikate gjeldende aktiviteter

src/main/java/no/nav/veilarbaktivitet/db/dao/AktivitetDAO.java, src/test/java/no/nav/veilarbaktivitet/db/dao/AktivitetDAOTest.java
Har også introdusert NamedParameterJdbcTemplate i AKtivitetDAO
https://trello.com/c/bozMxlfF
=> Test av transaksjonshåndtering i AktivitetDAO

src/main/java/no/nav/veilarbaktivitet/avtaltMedNav/AvtaltMedNavService.java, src/main/java/no/nav/veilarbaktivitet/db/dao/AktivitetDAO.java, src/main/java/no/nav/veilarbaktivitet/kvp/KVPAvsluttetService.java, src/main/java/no/nav/veilarbaktivitet/service/AktivitetService.java, src/test/java/no/nav/veilarbaktivitet/VeilarbAktivitetTestApp.java, src/test/java/no/nav/veilarbaktivitet/avtaltMedNav/AvtaltMedNavServiceTest.java, src/test/java/no/nav/veilarbaktivitet/avtaltMedNav/ForhaandsorienteringDAOTest.java, src/test/java/no/nav/veilarbaktivitet/avtaltMedNav/ForhaandsorienteringDTOControllerTest.java, src/test/java/no/nav/veilarbaktivitet/avtaltMedNav/varsel/AvtaltVarselServiceTest.java, src/test/java/no/nav/veilarbaktivitet/controller/AktivitetsplanRSTest.java, src/test/java/no/nav/veilarbaktivitet/db/dao/AktivitetDAOTest.java, src/test/java/no/nav/veilarbaktivitet/db/dao/KafkaAktivitetDAOTest.java, src/test/java/no/nav/veilarbaktivitet/db/dao/MoteSMSDAOTest.java, src/test/java/no/nav/veilarbaktivitet/motesms/MoteSMSServiceTest.java, src/test/java/no/nav/veilarbaktivitet/service/AktivitetServiceTest.java, src/test/java/no/nav/veilarbaktivitet/testutils/AktivitetDataTestBuilder.java, src/test/java/no/nav/veilarbaktivitet/testutils/InsertAktiviteter.java
=> Guard mot raceconditions under oppdatering av aktivitet

src/main/java/no/nav/veilarbaktivitet/mappers/AktivitetDTOMapper.java, src/test/java/no/nav/veilarbaktivitet/mappers/AktivitetDTOMapperTest.java
=> Ikke eksponere samtalereferat for ekstern bruker hvis ikke publisert

nais.yaml
=> Bugfix prod yaml

src/main/java/no/nav/veilarbaktivitet/oppfolging_status/OppfolgingStatusClientImpl.java, src/main/java/no/nav/veilarbaktivitet/oppfolging_status/OppfolgingStatusDTO.java, src/main/java/no/nav/veilarbaktivitet/stilling_fra_nav/OpprettForesporselOmDelingAvCv.java, src/test/java/no/nav/veilarbaktivitet/oppfolging_status/OppfolgingStatusDTOTest.java, src/test/java/no/nav/veilarbaktivitet/stilling_fra_nav/DelingAvCvITest.java, src/test/java/no/nav/veilarbaktivitet/stilling_fra_nav/OpprettForesporselOmDelingAvCvTest.java, src/test/resources/oppfolging_status/get-oppfolgingsstatus-response.json
=> Håndtere KRR reservasjon når man oppretter stilling fra nav

src/main/java/no/nav/veilarbaktivitet/service/AktivitetAppService.java, src/test/java/no/nav/veilarbaktivitet/service/AktivitetAppServiceTest.java
=> Oppdatering av etikett for aktivitet avbrutt eller fullført

src/main/java/no/nav/veilarbaktivitet/stilling_fra_nav/OpprettForesporselOmDelingAvCv.java, src/main/java/no/nav/veilarbaktivitet/stilling_fra_nav/StillingFraNavProducerClient.java
Litt mer logging for rekrutteringsbistand kafka tjenester
=> Rekr bistand logging

src/main/java/no/nav/veilarbaktivitet/db/dao/AktivitetDAO.java, src/main/java/no/nav/veilarbaktivitet/db/rowmappers/AktivitetDataRowMapper.java, src/main/java/no/nav/veilarbaktivitet/stilling_fra_nav/KontaktpersonData.java, src/main/java/no/nav/veilarbaktivitet/stilling_fra_nav/OpprettForesporselOmDelingAvCv.java, src/main/java/no/nav/veilarbaktivitet/stilling_fra_nav/StillingFraNavData.java, src/main/resources/db/migration/V1_49__rekruteringsbistand_kontaktperson.sql, src/test/java/no/nav/veilarbaktivitet/stilling_fra_nav/DelingAvCvITest.java, src/test/java/no/nav/veilarbaktivitet/testutils/AktivitetTypeDataTesBuilder.java
Vi må huske på å rydde opp i test-databasen
=> Lagt til kontaktperson

src/main/java/no/nav/veilarbaktivitet/aktivitet/AktivitetDAO.java, src/main/java/no/nav/veilarbaktivitet/aktivitet/AktivitetDataRowMapper.java, src/main/java/no/nav/veilarbaktivitet/config/database/Database.java, src/main/java/no/nav/veilarbaktivitet/stilling_fra_nav/CvKanDelesData.java, src/main/java/no/nav/veilarbaktivitet/stilling_fra_nav/DelingAvCvDTO.java, src/main/java/no/nav/veilarbaktivitet/stilling_fra_nav/DelingAvCvService.java, src/main/java/no/nav/veilarbaktivitet/stilling_fra_nav/StillingFraNavController.java, src/main/resources/db/migration/V1_54__cv_deling_avtalt_dato.sql, src/test/java/no/nav/veilarbaktivitet/arena/ArenaAktivitetConsumerTest.java, src/test/java/no/nav/veilarbaktivitet/stilling_fra_nav/StillingFraNavControllerITest.java, src/test/java/no/nav/veilarbaktivitet/stilling_fra_nav/StillingFraNavControllerTest.java
=> Svar på vegne av bruker

src/main/java/no/nav/veilarbaktivitet/brukernotifikasjon/kvitering/EksternVarslingKvitteringConsumer.java, src/main/java/no/nav/veilarbaktivitet/brukernotifikasjon/kvitering/KvitteringDAO.java, src/main/java/no/nav/veilarbaktivitet/brukernotifikasjon/kvitering/KvitteringMetrikk.java, src/test/java/no/nav/veilarbaktivitet/brukernotifikasjon/kvitering/BrukernotifikasjonKvitteringTest.java
=> brukernotifikasjonskvitteringsmetrikk tid brukt

src/main/java/no/nav/veilarbaktivitet/util/Frontendlogger.java, src/test/java/no/nav/veilarbaktivitet/util/FrontendloggerTest.java
Det fins et endepunkt i veilarbperson, men endepunktet støtter ikke autorisering fra id porten
=> Legger til endepunkt for frontendlogging

pom.xml, src/main/java/no/nav/veilarbaktivitet/person/AktorClientConfig.java
Tilgang gitt i prod: https://github.com/navikt/pdl/commit/7e86725ec5d4e675d142da6efb4ac8f3fce71a39
Tilgang gitt i Jira: https://jira.adeo.no/plugins/servlet/desk/portal/541/FAGSYSTEM-242240
=> Bump common og pdl M2M

src/main/java/no/nav/veilarbaktivitet/arena/VeilarbarenaClient.java, src/main/java/no/nav/veilarbaktivitet/config/HelsesjekkConfig.java, src/main/java/no/nav/veilarbaktivitet/config/OkHttpClientConfig.java, src/main/java/no/nav/veilarbaktivitet/kvp/v2/KvpV2ClientImpl.java, src/main/java/no/nav/veilarbaktivitet/manuell_status/v2/ManuellStatusV2ClientImpl.java, src/main/java/no/nav/veilarbaktivitet/nivaa4/Nivaa4ClientImpl.java, src/main/java/no/nav/veilarbaktivitet/oppfolging/client/OppfolgingV2ClientImpl.java, src/test/java/no/nav/veilarbaktivitet/arena/ArenaControllerTest.java, src/test/java/no/nav/veilarbaktivitet/config/ApplicationTestConfig.java, src/test/java/no/nav/veilarbaktivitet/nivaa4/Nivaa4ClientTest.java
Går over til å bruke Azure machine-to-machine auth på følgende backender
- veilarbarena
- veilarboppfolging
- veilarbperson
=> 🚀  Use Azure auth inside POAO and align tokenprovider configs

src/main/java/no/nav/veilarbaktivitet/aktivitetskort/test/AktivitetskortTestConsumer.java
=> fiks test consumer

src/main/java/no/nav/veilarbaktivitet/aktivitetskort/AktivitetsbestillingCreator.java, src/main/java/no/nav/veilarbaktivitet/aktivitetskort/feil/MessageIdIkkeUnikFeil.java, src/main/java/no/nav/veilarbaktivitet/aktivitetskort/feil/UlovligEndringFeil.java, src/main/java/no/nav/veilarbaktivitet/aktivitetskort/service/AktivitetskortService.java, src/test/java/no/nav/veilarbaktivitet/aktivitetskort/AktivitetsbestillingCreatorTest.java, src/test/java/no/nav/veilarbaktivitet/aktivitetskort/AktivitetskortConsumerIntegrationTest.java, src/test/java/no/nav/veilarbaktivitet/veilarbportefolje/AktiviteterTilKafkaAivenServiceTest.java, src/test/resources/__files/aktivitetskort/invalidaktivitetskortMessageIdEqualFunksjonellId.json
flere funksjonelle feil + tester
=> akaas mer validering

src/main/java/no/nav/veilarbaktivitet/arena/ArenaService.java, src/test/java/no/nav/veilarbaktivitet/arena/ArenaServiceTest.java
- Sorter på opprettet dato
- Fix sortering av FHO
=> arena fho sort fix

src/main/kotlin/no/nav/veilarbaktivitet/aktivitetskort/service/AktivitetskortService.kt, src/test/kotlin/no/nav/veilarbaktivitet/aktivitetskort/AktivitetskortConsumerIntegrationTest.kt
- **Tester**
- **Tillat oppdatering av historiske aktiviter hvis arena-kort**
=> tillat oppdateringer pa historiske fra acl

build.gradle.kts, src/main/java/no/nav/veilarbaktivitet/avtalt_med_nav/AvtaltMedNavController.java, src/main/kotlin/no/nav/veilarbaktivitet/aktivitet/AktivitetsplanController.kt, src/main/kotlin/no/nav/veilarbaktivitet/arena/ArenaController.kt, src/main/kotlin/no/nav/veilarbaktivitet/config/OwnerProvider.kt, src/main/kotlin/no/nav/veilarbaktivitet/config/ownerProviders/AktivitetOwnerProvider.kt, src/main/kotlin/no/nav/veilarbaktivitet/config/ownerProviders/ForhaandsorienteringOwnerProvider.kt, src/main/kotlin/no/nav/veilarbaktivitet/config/ownerProviders/OwnerProviderDAO.kt, src/test/java/no/nav/veilarbaktivitet/arena/ArenaControllerTest.java
- **Bruk ny annotation med owner-provider**
- **Fjerne unødvendig filtrering på hentAktivitetsVersjoner**
=> Bruk annotasjon som støtter owner-provider istedetfor fnr i url

nais/nais-dev-gcp.yaml, nais/nais-prod-gcp.yaml, src/main/java/no/nav/veilarbaktivitet/config/OkHttpClientConfig.java
Reverts navikt/veilarbaktivitet#817
=> Revert "Bruk veilarboppfolging i gcp"

build.gradle.kts, src/main/java/no/nav/veilarbaktivitet/avtalt_med_nav/AvtaltMedNavController.java, src/main/java/no/nav/veilarbaktivitet/internapi/InternApiService.java, src/main/java/no/nav/veilarbaktivitet/stilling_fra_nav/StillingFraNavController.java, src/main/kotlin/no/nav/veilarbaktivitet/aktivitet/AktivitetsplanController.kt, src/main/kotlin/no/nav/veilarbaktivitet/aktivitetskort/graphql/AktivitetskortController.kt, src/main/kotlin/no/nav/veilarbaktivitet/arena/ArenaController.kt, src/main/kotlin/no/nav/veilarbaktivitet/arkivering/ArkiveringsController.kt, src/main/kotlin/no/nav/veilarbaktivitet/foresatteinnsynsrett/InnsynrettController.kt, src/test/java/no/nav/veilarbaktivitet/arena/ArenaControllerTest.java, src/test/java/no/nav/veilarbaktivitet/avtalt_med_nav/ForhaandsorienteringDTOControllerTest.java, src/test/java/no/nav/veilarbaktivitet/service/AuthServiceTest.java
Sjekk for skrivetilgang i AuthorizeFnr annotasjon
=> Bump dab common

build.gradle.kts, src/main/java/no/nav/veilarbaktivitet/aktivitet/mappers/Helpers.java
Bruker apache collections i stedet som ikke har kritisk sårbarhet
=> Erstatte generic-collections

src/main/java/no/nav/veilarbaktivitet/veilarbportefolje/dto/AktivitetTypeDTO.java, src/main/kotlin/no/nav/veilarbaktivitet/aktivitetskort/dto/AktivitetskortType.kt, src/main/kotlin/no/nav/veilarbaktivitet/arkivering/mapper/AktivitetDtoToArkivPayload.kt, src/main/resources/schemas/akaas/Aktivitetskort.V1.shared-definitions.schema.yml, src/test/kotlin/no/nav/veilarbaktivitet/aktivitetskort/AktivitetskortConsumerIntegrationTest.kt
Husk å fikse aktivitetskort type i frontend før merge
https://github.com/navikt/aktivitetsplan/pull/1326
=> Støtte for ARBEIDSTRENING i akaas
